---

- import_tasks: install.yml
  tags:
    - system
    - users-oh-my-zsh
    - install
    - install-users-oh-my-zsh

- import_tasks: config.yml
  tags:
    - system
    - users-oh-my-zsh
    - config
    - config-users-oh-my-zsh
